# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class ActivityFetchError(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A generic error for file activities endpoint
    """


    class MetaOapg:
        required = {
            "activity_type",
            "error",
        }
        
        class properties:
            
            
            class activity_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "annotation": "ANNOTATION",
                        "app_activity": "APP_ACTIVITY",
                        "comment": "COMMENT",
                        "task": "TASK",
                        "versions": "VERSIONS",
                    }
                
                @schemas.classproperty
                def ANNOTATION(cls):
                    return cls("annotation")
                
                @schemas.classproperty
                def APP_ACTIVITY(cls):
                    return cls("app_activity")
                
                @schemas.classproperty
                def COMMENT(cls):
                    return cls("comment")
                
                @schemas.classproperty
                def TASK(cls):
                    return cls("task")
                
                @schemas.classproperty
                def VERSIONS(cls):
                    return cls("versions")
        
            @staticmethod
            def error() -> typing.Type['ClientError']:
                return ClientError
            __annotations__ = {
                "activity_type": activity_type,
                "error": error,
            }
    
    activity_type: MetaOapg.properties.activity_type
    error: 'ClientError'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activity_type"]) -> MetaOapg.properties.activity_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'ClientError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["activity_type", "error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activity_type"]) -> MetaOapg.properties.activity_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> 'ClientError': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["activity_type", "error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        activity_type: typing.Union[MetaOapg.properties.activity_type, str, ],
        error: 'ClientError',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ActivityFetchError':
        return super().__new__(
            cls,
            *args,
            activity_type=activity_type,
            error=error,
            _configuration=_configuration,
            **kwargs,
        )

from box_python_sdk.model.client_error import ClientError
