# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class AnnotationTargetPathGroup(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Annotation target path group.
    """


    class MetaOapg:
        required = {
            "paths",
            "stroke",
        }
        
        class properties:
            
            
            class paths(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AnnotationTargetPath']:
                        return AnnotationTargetPath
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AnnotationTargetPath'], typing.List['AnnotationTargetPath']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'paths':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AnnotationTargetPath':
                    return super().__getitem__(i)
        
            @staticmethod
            def stroke() -> typing.Type['AnnotationTargetStroke']:
                return AnnotationTargetStroke
            __annotations__ = {
                "paths": paths,
                "stroke": stroke,
            }
    
    paths: MetaOapg.properties.paths
    stroke: 'AnnotationTargetStroke'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paths"]) -> MetaOapg.properties.paths: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stroke"]) -> 'AnnotationTargetStroke': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["paths", "stroke", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paths"]) -> MetaOapg.properties.paths: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stroke"]) -> 'AnnotationTargetStroke': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["paths", "stroke", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        paths: typing.Union[MetaOapg.properties.paths, list, tuple, ],
        stroke: 'AnnotationTargetStroke',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AnnotationTargetPathGroup':
        return super().__new__(
            cls,
            *args,
            paths=paths,
            stroke=stroke,
            _configuration=_configuration,
            **kwargs,
        )

from box_python_sdk.model.annotation_target_path import AnnotationTargetPath
from box_python_sdk.model.annotation_target_stroke import AnnotationTargetStroke
