# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class Invite(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An invite for a user to an enterprise.
    """


    class MetaOapg:
        required = {
            "id",
            "type",
        }
        
        class properties:
            id = schemas.StrSchema
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "invite": "INVITE",
                    }
                
                @schemas.classproperty
                def INVITE(cls):
                    return cls("invite")
        
            @staticmethod
            def invited_to() -> typing.Type['InviteInvitedTo']:
                return InviteInvitedTo
        
            @staticmethod
            def actionable_by() -> typing.Type['UserMini']:
                return UserMini
        
            @staticmethod
            def invited_by() -> typing.Type['UserMini']:
                return UserMini
            status = schemas.StrSchema
            created_at = schemas.DateTimeSchema
            modified_at = schemas.DateTimeSchema
            __annotations__ = {
                "id": id,
                "type": type,
                "invited_to": invited_to,
                "actionable_by": actionable_by,
                "invited_by": invited_by,
                "status": status,
                "created_at": created_at,
                "modified_at": modified_at,
            }
    
    id: MetaOapg.properties.id
    type: MetaOapg.properties.type
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invited_to"]) -> 'InviteInvitedTo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["actionable_by"]) -> 'UserMini': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invited_by"]) -> 'UserMini': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modified_at"]) -> MetaOapg.properties.modified_at: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "type", "invited_to", "actionable_by", "invited_by", "status", "created_at", "modified_at", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invited_to"]) -> typing.Union['InviteInvitedTo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["actionable_by"]) -> typing.Union['UserMini', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invited_by"]) -> typing.Union['UserMini', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modified_at"]) -> typing.Union[MetaOapg.properties.modified_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "type", "invited_to", "actionable_by", "invited_by", "status", "created_at", "modified_at", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        invited_to: typing.Union['InviteInvitedTo', schemas.Unset] = schemas.unset,
        actionable_by: typing.Union['UserMini', schemas.Unset] = schemas.unset,
        invited_by: typing.Union['UserMini', schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, datetime, schemas.Unset] = schemas.unset,
        modified_at: typing.Union[MetaOapg.properties.modified_at, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Invite':
        return super().__new__(
            cls,
            *args,
            id=id,
            type=type,
            invited_to=invited_to,
            actionable_by=actionable_by,
            invited_by=invited_by,
            status=status,
            created_at=created_at,
            modified_at=modified_at,
            _configuration=_configuration,
            **kwargs,
        )

from box_python_sdk.model.invite_invited_to import InviteInvitedTo
from box_python_sdk.model.user_mini import UserMini
