# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class LegalHoldPoliciesCreateNewPolicyRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "policy_name",
        }
        
        class properties:
            
            
            class policy_name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 254
            
            
            class description(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 500
            
            
            class filter_started_at(
                schemas.DateTimeSchema
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
                    max_length = 500
            
            
            class filter_ended_at(
                schemas.DateTimeSchema
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
                    max_length = 500
            is_ongoing = schemas.BoolSchema
            __annotations__ = {
                "policy_name": policy_name,
                "description": description,
                "filter_started_at": filter_started_at,
                "filter_ended_at": filter_ended_at,
                "is_ongoing": is_ongoing,
            }
    
    policy_name: MetaOapg.properties.policy_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["policy_name"]) -> MetaOapg.properties.policy_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter_started_at"]) -> MetaOapg.properties.filter_started_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter_ended_at"]) -> MetaOapg.properties.filter_ended_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_ongoing"]) -> MetaOapg.properties.is_ongoing: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["policy_name", "description", "filter_started_at", "filter_ended_at", "is_ongoing", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["policy_name"]) -> MetaOapg.properties.policy_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter_started_at"]) -> typing.Union[MetaOapg.properties.filter_started_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter_ended_at"]) -> typing.Union[MetaOapg.properties.filter_ended_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_ongoing"]) -> typing.Union[MetaOapg.properties.is_ongoing, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["policy_name", "description", "filter_started_at", "filter_ended_at", "is_ongoing", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        policy_name: typing.Union[MetaOapg.properties.policy_name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        filter_started_at: typing.Union[MetaOapg.properties.filter_started_at, str, datetime, schemas.Unset] = schemas.unset,
        filter_ended_at: typing.Union[MetaOapg.properties.filter_ended_at, str, datetime, schemas.Unset] = schemas.unset,
        is_ongoing: typing.Union[MetaOapg.properties.is_ongoing, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LegalHoldPoliciesCreateNewPolicyRequest':
        return super().__new__(
            cls,
            *args,
            policy_name=policy_name,
            description=description,
            filter_started_at=filter_started_at,
            filter_ended_at=filter_ended_at,
            is_ongoing=is_ongoing,
            _configuration=_configuration,
            **kwargs,
        )
