# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class PostInvitesRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "enterprise",
            "actionable_by",
        }
        
        class properties:
        
            @staticmethod
            def enterprise() -> typing.Type['PostInvitesRequestEnterprise']:
                return PostInvitesRequestEnterprise
        
            @staticmethod
            def actionable_by() -> typing.Type['PostInvitesRequestActionableBy']:
                return PostInvitesRequestActionableBy
            __annotations__ = {
                "enterprise": enterprise,
                "actionable_by": actionable_by,
            }
    
    enterprise: 'PostInvitesRequestEnterprise'
    actionable_by: 'PostInvitesRequestActionableBy'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enterprise"]) -> 'PostInvitesRequestEnterprise': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["actionable_by"]) -> 'PostInvitesRequestActionableBy': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["enterprise", "actionable_by", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enterprise"]) -> 'PostInvitesRequestEnterprise': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["actionable_by"]) -> 'PostInvitesRequestActionableBy': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["enterprise", "actionable_by", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        enterprise: 'PostInvitesRequestEnterprise',
        actionable_by: 'PostInvitesRequestActionableBy',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PostInvitesRequest':
        return super().__new__(
            cls,
            *args,
            enterprise=enterprise,
            actionable_by=actionable_by,
            _configuration=_configuration,
            **kwargs,
        )

from box_python_sdk.model.post_invites_request_actionable_by import PostInvitesRequestActionableBy
from box_python_sdk.model.post_invites_request_enterprise import PostInvitesRequestEnterprise
