# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from box_python_sdk import schemas  # noqa: F401


class RetentionPolicyAssignment(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A retention assignment represents a rule specifying
the files a retention policy retains.
Assignments can retain files based on their folder or metadata,
or hold all files in the enterprise.
    """


    class MetaOapg:
        required = {
            "id",
            "type",
        }
        
        class properties:
            id = schemas.StrSchema
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "retention_policy_assignment": "RETENTION_POLICY_ASSIGNMENT",
                    }
                
                @schemas.classproperty
                def RETENTION_POLICY_ASSIGNMENT(cls):
                    return cls("retention_policy_assignment")
            
            
            class retention_policy(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    all_of_1 = schemas.AnyTypeSchema
                    
                    @classmethod
                    @functools.lru_cache()
                    def all_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            RetentionPolicyMini,
                            cls.all_of_1,
                        ]
            
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'retention_policy':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                        **kwargs,
                    )
        
            @staticmethod
            def assigned_to() -> typing.Type['RetentionPolicyAssignmentAssignedTo']:
                return RetentionPolicyAssignmentAssignedTo
        
            @staticmethod
            def filter_fields() -> typing.Type['RetentionPolicyAssignmentFilterFields']:
                return RetentionPolicyAssignmentFilterFields
            
            
            class assigned_by(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    all_of_1 = schemas.AnyTypeSchema
                    
                    @classmethod
                    @functools.lru_cache()
                    def all_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            UserMini,
                            cls.all_of_1,
                        ]
            
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'assigned_by':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            assigned_at = schemas.DateTimeSchema
            start_date_field = schemas.StrSchema
            __annotations__ = {
                "id": id,
                "type": type,
                "retention_policy": retention_policy,
                "assigned_to": assigned_to,
                "filter_fields": filter_fields,
                "assigned_by": assigned_by,
                "assigned_at": assigned_at,
                "start_date_field": start_date_field,
            }
    
    id: MetaOapg.properties.id
    type: MetaOapg.properties.type
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["retention_policy"]) -> MetaOapg.properties.retention_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigned_to"]) -> 'RetentionPolicyAssignmentAssignedTo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter_fields"]) -> 'RetentionPolicyAssignmentFilterFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigned_by"]) -> MetaOapg.properties.assigned_by: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigned_at"]) -> MetaOapg.properties.assigned_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_date_field"]) -> MetaOapg.properties.start_date_field: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "type", "retention_policy", "assigned_to", "filter_fields", "assigned_by", "assigned_at", "start_date_field", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["retention_policy"]) -> typing.Union[MetaOapg.properties.retention_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigned_to"]) -> typing.Union['RetentionPolicyAssignmentAssignedTo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter_fields"]) -> typing.Union['RetentionPolicyAssignmentFilterFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigned_by"]) -> typing.Union[MetaOapg.properties.assigned_by, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigned_at"]) -> typing.Union[MetaOapg.properties.assigned_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_date_field"]) -> typing.Union[MetaOapg.properties.start_date_field, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "type", "retention_policy", "assigned_to", "filter_fields", "assigned_by", "assigned_at", "start_date_field", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        retention_policy: typing.Union[MetaOapg.properties.retention_policy, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        assigned_to: typing.Union['RetentionPolicyAssignmentAssignedTo', schemas.Unset] = schemas.unset,
        filter_fields: typing.Union['RetentionPolicyAssignmentFilterFields', schemas.Unset] = schemas.unset,
        assigned_by: typing.Union[MetaOapg.properties.assigned_by, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        assigned_at: typing.Union[MetaOapg.properties.assigned_at, str, datetime, schemas.Unset] = schemas.unset,
        start_date_field: typing.Union[MetaOapg.properties.start_date_field, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RetentionPolicyAssignment':
        return super().__new__(
            cls,
            *args,
            id=id,
            type=type,
            retention_policy=retention_policy,
            assigned_to=assigned_to,
            filter_fields=filter_fields,
            assigned_by=assigned_by,
            assigned_at=assigned_at,
            start_date_field=start_date_field,
            _configuration=_configuration,
            **kwargs,
        )

from box_python_sdk.model.retention_policy_assignment_assigned_to import RetentionPolicyAssignmentAssignedTo
from box_python_sdk.model.retention_policy_assignment_filter_fields import RetentionPolicyAssignmentFilterFields
from box_python_sdk.model.retention_policy_mini import RetentionPolicyMini
from box_python_sdk.model.user_mini import UserMini
