from box_python_sdk.paths.folders_folder_id_metadata_enterprise_security_classification_6_vm_vochw_uwo.get import ApiForget
from box_python_sdk.paths.folders_folder_id_metadata_enterprise_security_classification_6_vm_vochw_uwo.put import ApiForput
from box_python_sdk.paths.folders_folder_id_metadata_enterprise_security_classification_6_vm_vochw_uwo.post import ApiForpost
from box_python_sdk.paths.folders_folder_id_metadata_enterprise_security_classification_6_vm_vochw_uwo.delete import ApiFordelete


class FoldersFolderIdMetadataEnterpriseSecurityClassification6VMVochwUWo(
    ApiForget,
    ApiForput,
    ApiForpost,
    ApiFordelete,
):
    pass
