from box_python_sdk.paths.shield_information_barrier_segment_members_shield_information_barrier_segment_member_id.get import ApiForget
from box_python_sdk.paths.shield_information_barrier_segment_members_shield_information_barrier_segment_member_id.delete import ApiFordelete


class ShieldInformationBarrierSegmentMembersShieldInformationBarrierSegmentMemberId(
    ApiForget,
    ApiFordelete,
):
    pass
