# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from box_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    METADATA_TEMPLATES = "Metadata templates"
    UPLOADS_CHUNKED = "Uploads (Chunked)"
    FILES = "Files"
    FOLDERS = "Folders"
    GROUP_MEMBERSHIPS = "Group memberships"
    LEGAL_HOLD_POLICY_ASSIGNMENTS = "Legal hold policy assignments"
    RETENTION_POLICY_ASSIGNMENTS = "Retention policy assignments"
    USERS = "Users"
    SIGN_REQUESTS = "Sign requests"
    COMMENTS = "Comments"
    FILE_VERSIONS = "File versions"
    GROUPS = "Groups"
    LEGAL_HOLD_POLICIES = "Legal hold policies"
    METADATA_CASCADE_POLICIES = "Metadata cascade policies"
    METADATA_INSTANCES_FILES = "Metadata instances (Files)"
    METADATA_INSTANCES_FOLDERS = "Metadata instances (Folders)"
    RETENTION_POLICIES = "Retention policies"
    SHARED_LINKS_FILES = "Shared links (Files)"
    SHARED_LINKS_FOLDERS = "Shared links (Folders)"
    SHARED_LINKS_WEB_LINKS = "Shared links (Web Links)"
    SHIELD_INFORMATION_BARRIER_SEGMENTS = "Shield information barrier segments"
    SKILLS = "Skills"
    STANDARD_AND_ZONES_STORAGE_POLICY_ASSIGNMENTS = "Standard and Zones Storage Policy Assignments"
    TASK_ASSIGNMENTS = "Task assignments"
    TASKS = "Tasks"
    WEBHOOKS = "Webhooks"
    AUTHORIZATION = "Authorization"
    CLASSIFICATIONS = "Classifications"
    CLASSIFICATIONS_ON_FILES = "Classifications on files"
    CLASSIFICATIONS_ON_FOLDERS = "Classifications on folders"
    COLLABORATIONS = "Collaborations"
    COLLABORATIONS_LIST = "Collaborations (List)"
    DOMAIN_RESTRICTIONS_USER_EXEMPTIONS = "Domain restrictions (User exemptions)"
    DOMAIN_RESTRICTIONS_FOR_COLLABORATIONS = "Domain restrictions for collaborations"
    FILE_REQUESTS = "File requests"
    INTEGRATION_MAPPINGS = "Integration mappings"
    SHIELD_INFORMATION_BARRIERS = "Shield information barriers"
    SHIELD_INFORMATION_BARRIER_SEGMENT_MEMBERS = "Shield information barrier segment members"
    SHIELD_INFORMATION_BARRIER_SEGMENT_RESTRICTIONS = "Shield information barrier segment restrictions"
    TERMS_OF_SERVICE = "Terms of service"
    WEB_LINKS = "Web links"
    DEVICE_PINNERS = "Device pinners"
    EMAIL_ALIASES = "Email aliases"
    FOLDER_LOCKS = "Folder Locks"
    SHIELD_INFORMATION_BARRIER_REPORTS = "Shield information barrier reports"
    TERMS_OF_SERVICE_USER_STATUSES = "Terms of service user statuses"
    TRASHED_FILES = "Trashed files"
    TRASHED_FOLDERS = "Trashed folders"
    TRASHED_WEB_LINKS = "Trashed web links"
    USER_AVATARS = "User avatars"
    WATERMARKS_FILES = "Watermarks (Files)"
    WATERMARKS_FOLDERS = "Watermarks (Folders)"
    ZIP_DOWNLOADS = "Zip Downloads"
    COLLECTIONS = "Collections"
    EVENTS = "Events"
    FILE_VERSION_LEGAL_HOLDS = "File version legal holds"
    FILE_VERSION_RETENTIONS = "File version retentions"
    INVITES = "Invites"
    SEARCH = "Search"
    SESSION_TERMINATION = "Session termination"
    SIGN_TEMPLATES = "Sign templates"
    STANDARD_AND_ZONES_STORAGE_POLICIES = "Standard and Zones Storage Policies"
    UPLOADS = "Uploads"
    WORKFLOWS = "Workflows"
    DOWNLOADS = "Downloads"
    FILE_ACTIVITIES = "File activities"
    RECENT_ITEMS = "Recent items"
    TRANSFER_FOLDERS = "Transfer folders"
    TRASHED_ITEMS = "Trashed items"
