# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.comments.post import Comments
from box_python_sdk.paths.comments_comment_id.get import GetById
from box_python_sdk.paths.files_file_id_comments.get import ListFileComments
from box_python_sdk.paths.comments_comment_id.delete import RemoveById
from box_python_sdk.paths.comments_comment_id.put import UpdateMessage
from box_python_sdk.apis.tags.comments_api_raw import CommentsApiRaw


class CommentsApi(
    Comments,
    GetById,
    ListFileComments,
    RemoveById,
    UpdateMessage,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CommentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CommentsApiRaw(api_client)
