# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.metadata_cascade_policies_metadata_cascade_policy_id_apply.post import ApplyToChildren
from box_python_sdk.paths.metadata_cascade_policies.post import CreatePolicy
from box_python_sdk.paths.metadata_cascade_policies_metadata_cascade_policy_id.get import GetPolicyAssignedToFolder
from box_python_sdk.paths.metadata_cascade_policies.get import List
from box_python_sdk.paths.metadata_cascade_policies_metadata_cascade_policy_id.delete import RemovePolicy
from box_python_sdk.apis.tags.metadata_cascade_policies_api_raw import MetadataCascadePoliciesApiRaw


class MetadataCascadePoliciesApi(
    ApplyToChildren,
    CreatePolicy,
    GetPolicyAssignedToFolder,
    List,
    RemovePolicy,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MetadataCascadePoliciesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MetadataCascadePoliciesApiRaw(api_client)
