# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.recent_items.get import ListAccessedItems
from box_python_sdk.apis.tags.recent_items_api_raw import RecentItemsApiRaw


class RecentItemsApi(
    ListAccessedItems,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RecentItemsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RecentItemsApiRaw(api_client)
