# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.files_file_idadd_shared_link.put import AddSharedLinkToFileRaw
from box_python_sdk.paths.shared_items.get import GetBySharedLinkRaw
from box_python_sdk.paths.files_file_idget_shared_link.get import GetSharedLinkInfoRaw
from box_python_sdk.paths.files_file_idremove_shared_link.put import RemoveSharedLinkRaw
from box_python_sdk.paths.files_file_idupdate_shared_link.put import UpdateLinkOnFileRaw


class SharedLinksFilesApiRaw(
    AddSharedLinkToFileRaw,
    GetBySharedLinkRaw,
    GetSharedLinkInfoRaw,
    RemoveSharedLinkRaw,
    UpdateLinkOnFileRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
