# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.shield_information_barrier_segment_members.post import CreateNewMember
from box_python_sdk.paths.shield_information_barrier_segment_members_shield_information_barrier_segment_member_id.get import GetById
from box_python_sdk.paths.shield_information_barrier_segment_members.get import ListSegmentMembersBasedOnIds
from box_python_sdk.paths.shield_information_barrier_segment_members_shield_information_barrier_segment_member_id.delete import RemoveById
from box_python_sdk.apis.tags.shield_information_barrier_segment_members_api_raw import ShieldInformationBarrierSegmentMembersApiRaw


class ShieldInformationBarrierSegmentMembersApi(
    CreateNewMember,
    GetById,
    ListSegmentMembersBasedOnIds,
    RemoveById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ShieldInformationBarrierSegmentMembersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ShieldInformationBarrierSegmentMembersApiRaw(api_client)
