# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.task_assignments.post import AssignMultipleUsers
from box_python_sdk.paths.task_assignments_task_assignment_id.delete import DeleteSpecificAssignment
from box_python_sdk.paths.task_assignments_task_assignment_id.get import GetTaskAssignmentInfo
from box_python_sdk.paths.tasks_task_id_assignments.get import ListForTask
from box_python_sdk.paths.task_assignments_task_assignment_id.put import UpdateStateAssignedToUser
from box_python_sdk.apis.tags.task_assignments_api_raw import TaskAssignmentsApiRaw


class TaskAssignmentsApi(
    AssignMultipleUsers,
    DeleteSpecificAssignment,
    GetTaskAssignmentInfo,
    ListForTask,
    UpdateStateAssignedToUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TaskAssignmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TaskAssignmentsApiRaw(api_client)
