# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.users_user_id_folders_0.put import ToDestination
from box_python_sdk.apis.tags.transfer_folders_api_raw import TransferFoldersApiRaw


class TransferFoldersApi(
    ToDestination,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TransferFoldersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TransferFoldersApiRaw(api_client)
