# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.folders_folder_id_trash.get import GetdFolder
from box_python_sdk.paths.folders_folder_id_trash.delete import PermanentlyRemoveFolder
from box_python_sdk.paths.folders_folder_id.post import RestoreFolder
from box_python_sdk.apis.tags.trashed_folders_api_raw import TrashedFoldersApiRaw


class TrashedFoldersApi(
    GetdFolder,
    PermanentlyRemoveFolder,
    RestoreFolder,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TrashedFoldersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TrashedFoldersApiRaw(api_client)
