# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.files_file_id_watermark.put import ApplyWatermarkToFile
from box_python_sdk.paths.files_file_id_watermark.get import Get
from box_python_sdk.paths.files_file_id_watermark.delete import RemoveWatermark
from box_python_sdk.apis.tags.watermarks_files_api_raw import WatermarksFilesApiRaw


class WatermarksFilesApi(
    ApplyWatermarkToFile,
    Get,
    RemoveWatermark,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WatermarksFilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WatermarksFilesApiRaw(api_client)
