# coding: utf-8

"""
    Box Platform API

    [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

    The version of the OpenAPI document: 2.0.0
    Contact: devrel@box.com
    Created by: https://box.dev
"""

from box_python_sdk.paths.web_links.post import CreateObject
from box_python_sdk.paths.web_links_web_link_id.get import GetInformation
from box_python_sdk.paths.web_links_web_link_id.delete import RemoveLink
from box_python_sdk.paths.web_links_web_link_id.put import UpdateObject
from box_python_sdk.apis.tags.web_links_api_raw import WebLinksApiRaw


class WebLinksApi(
    CreateObject,
    GetInformation,
    RemoveLink,
    UpdateObject,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebLinksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebLinksApiRaw(api_client)
